apiVersion: v1
kind: Service
metadata:
  name: consul-service
  namespace: bookstore
spec:
  selector:
    app: consul
  ports:
    - name: http
      port: 8500
      targetPort: 8500
    - name: grpc
      port: 8502
      targetPort: 8502
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
  namespace: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
        - name: consul
          image: consul:1.15
          args: ["agent", "-dev", "-client=0.0.0.0"]
          ports:
            - containerPort: 8500
            - containerPort: 8502
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
